<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Symitar</string>

    <key>fileTypes</key>
    <array>
        <string>RB</string>
        <string>RD</string>
        <string>PRO</string>
        <string>DEF</string>
        <string>SET</string>
    </array>
    <key>foldingStartMarker</key>
    <string>((Define|Setup|Select|Sort|Print|Procedure|Total)\s*(//.*)?$)</string>
    <key>foldingStopMarker</key>
    <string>^\s*End</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\[((NOTE:|Note:)([$-/:-?{-~!"^_`\.\s\w]*))\]</string>
            <key>name</key>
            <string>comment.line.symitar</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.line.note.symitar</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\[((?&lt;=\[)(!)([$-/:-?{-~!"^_`\.\s\w]*))\]</string>
            <key>name</key>
            <string>comment.line.symitar</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.line.important.symitar</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\[((ToDo:|Todo:|TODO:)([$-/:-?{-~!"^_`\.\s\w]*))\]</string>
            <key>name</key>
            <string>comment.line.symitar</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.line.todo.symitar</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\[(.*)\]</string>
            <key>name</key>
            <string>comment.block.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>&lt;&lt;=|%=|&amp;=|\*=|\*\*=|\+=|\-=|\^=|\|{1,2}=|&lt;&lt;</string>
            <key>name</key>
            <string>keyword.operator.assignment.augmented.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>&lt;=&gt;|&lt;(?!&lt;|=)|&gt;(?!&lt;|=|&gt;)|&lt;=|&gt;=|===|==|=~|!=|!~|(?&lt;=[ \t])\?</string>
            <key>name</key>
            <string>keyword.operator.comparison.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;=[ \t])!+|\bNot\b|&amp;&amp;|\bAnd\b|\|\||\bOr\b|\^</string>
            <key>name</key>
            <string>keyword.operator.logical.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(%|&amp;|\*\*|\*|\+|\-|/)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\||~|&gt;&gt;</string>
            <key>name</key>
            <string>keyword.operator.other.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>([a-zA-Z]+|[0-9]+)(?=:)</string>
            <key>name</key>
            <string>keyword.controller.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;=:)([a-zA-Z]+|[0-9]+)</string>
            <key>name</key>
            <string>constant.other.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>([a-zA-Z]+|[0-9]+)(?=\(.*\))</string>
            <key>name</key>
            <string>entity.name.function.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(Target|Define|Setup|Select|Sort|Print|Total|Procedure|Call|Suppress|Windows|Subroutine|Demand|If|Then|Do|End|Else|For|While|To|Set|FMPerform)\b(?![?!])</string>
            <key>name</key>
            <string>keyword.control.symitar</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?i)(Character|Date|Number|Code|Money|Rate)\b</string>
            <key>name</key>
            <string>support.type.symitar</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.preprocessor.symitar</string>
                </dict>
            </dict>
            <key>match</key>
            <string>#(INCLUDE)\b(?:\s*([^ ;$]+))/i</string>
            <key>name</key>
            <string>meta.include.symitar</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.symitar</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>double quoted string</string>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.symitar</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.symitar</string>
        </dict>
    </array>

    <key>scopeName</key>
    <string>source.symitar</string>

    <key>uuid</key>
    <string>959814ed-12b5-4e71-b684-82ee6774039d</string>
  </dict>
</plist>
